### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by liangzaiovo** [chendiqian/GNN4FL#1]
Hello, can you provide the pdf file of this paper？

**Comment by chendiqian** [comment]
Thank you for your interest, our paper will be available soon on IEEE Xplore.

**Comment by liangzaiovo** [comment]
Received, thank you.




黄远伸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chendiqian/GNN4FL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chendiqian/GNN4FL] paper (Issue #1)





 
Thank you for your interest, our paper will be available soon on IEEE Xplore.

**Comment by chendiqian** [comment]
It is now available on arxiv https://arxiv.org/abs/2309.05525

**Comment by liangzaiovo** [comment]
Thanks a lot!
